#4feb2024
#educ8720
#Derek Briggs (Note: updated version based on earlier script from Ben Shear)

# Install packages below if not already installed.
#install.packages(CTT)
library(CTT)
library(mirt)
library(latticeExtra)
library(psych)

###PART 1##################################################################

# update this for your computer!
data_path <- "~/Users/briggsd/Library/CloudStorage/Dropbox/Github/Measurement and Psychometrics/IRT Models for Dichotomously Scored Items/Data"

# Import data----

forma <- read.csv(paste0(data_path, "pset1_formA.csv"))
head(forma)
forma <- forma[,1:15]  # We will only use first 15 items

################################################################################
# Always start with descriptive statistics before doing anything fancy
# In this context, descriptive stats are classical item stats
# Use the "alpha" function in the psych package.

alpha(forma)

# Use the function cttICC from the package "CTT"
# to make empirical ICC plots based on observed total scores
# Example: 

cttICC(scores = apply(forma, 1, sum), itemVector = forma[,1])

# Doing this for all 15 items

par(mfrow = c(1,3))  #Sets graphics parameter to show three plots in one row
for (i in 0:4) {    #Outer loop to run this 5 times
  for (j in 1:3) {   #Inner loop to produce plots in sets of 3
    cttICC(scores = apply(forma, 1, sum), itemVector = forma[,paste0("V", 3*i+j)],
           plotTitle = paste0("Item ", 3*i+j)) 
  }
}
par(mfrow = c(1,1))

################################################################################
# look at dimensionality briefly
plot(eigen(cor(forma))$values, type = "b", las = 1)

# some signs of a second dimension


## END of PART 1 ###############################################################


## PART 2 Using the package "mirt" to fit the 1/2/3PL models to the data###----

# estimate 1/2/3PL models
mirt_1pl <- mirt(forma, model = 1, itemtype = "Rasch", method = "EM")
mirt_2pl <- mirt(forma, model = 1, itemtype = "2PL", method = "EM")
mirt_3pl <- mirt(forma, model = 1, itemtype = "3PL", method = "EM")

# use the coef() function to see the estimates
# note by default they are in slope-intercept form!
coef(mirt_2pl, simplify=TRUE)
# use IRTpars=TRUE to get the usual IRT form
coef(mirt_2pl, simplify=TRUE, IRTpars=TRUE)
#b=-d/a; 0.768=-(-1.707/2.223)

# if you save the coef object you can extract a nicer table
# note: getting standard errors is more complex; we'll do that later
coef_2pl <- coef(mirt_2pl, simplify=TRUE, IRTpars=TRUE)
coef_2pl$items
# the g and u are additional item parameters not estimated
# g = guessing parameter, u = upper asymptote (for a 4PL!)

coef_2pl$items[,1:2]

# we can look at the estimates side-by-side
# note that the 1pl estimates are on a different scale
coef_1pl <- coef(mirt_1pl, simplify=TRUE, IRTpars=TRUE)
coef_3pl <- coef(mirt_3pl, simplify=TRUE, IRTpars=TRUE)

# clearly some issues with the 3pl that need to be diagnosed
round(data.frame(coef_1pl$items[,1:2],
           coef_2pl$items[,1:2],
           coef_3pl$items[,1:3]), 3)

# we can see that b-values are highly correlated
# differences up to a linear transformation are just due to scale
plot(coef_1pl$items[,2]~coef_2pl$items[,2])

################################################################################
# make some plots
help('plot-method') # see the various mirt plot functions

# let's go with the 2pl for now
# show IRFs
plot(mirt_2pl, type='trace')

#Specific items
plot(mirt_2pl, which.items = 3,type='trace')
plot(mirt_2pl, which.items = 3:5,type='trace')
plot(mirt_2pl, which.items = c(1,3,8),type='trace')

# Can you create your own plots using the ICCplot function from 
# Baker & Kim's Chapter 2?
# You will need to extract the relevant item parameters from the objects
# generated by running mirt.

# look at observed vs predicted response probabilities
itemfit(mirt_2pl, group.bins=15, empirical.plot = 1)

## END of PART 2 ###############################################################

## PART 3 Test Characteristic Curve and Information Function################

# show TCC
plot(mirt_2pl)

# show 3 item info plots
plot(mirt_2pl, type='infotrace', which.items=c(1:3))

# show test info
plot(mirt_2pl, type='info')

# show test info and SEM
plot(mirt_2pl, type='infoSE', theta_lim=c(-3,3))   #This function only works with latest R version



